version: "3.4"
services:
  mysqldb:
    image: mysql:8.0.30
    container_name: mysqldb
    environment:
      MYSQL_DATABASE: hunnid_blog
      MYSQL_ROOT_PASSWORD: 12345678
    restart: unless-stopped
    ports :
      - '3307:3306'
    networks:
      - app_network
    volumes:
      - db_data:/var/lib/mysql
  spring-app:
    depends_on:
      - mysqldb
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysqldb:3306/hunnid_blog?useSSL=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 12345678
    build:
      context: ./
    ports:
      - '8089:8089'
    networks:
      - app_network
networks:
  app_network:
    driver: bridge
volumes:
  db_data: